REPORT_SPEC = {
    "version": "2.0.0",
    "updatedAt": "2026-04-05",
    "description": "AiModa Fashion Report Zip 规范 - 以 manifest + entryHtml + required cover 为核心",
    "folderStructure": {
        "root": "{report-root}/",
        "required": ["manifest.json", "entryHtml", "cover image"],
        "optional": ["additional html pages", "assets/", "features file"],
        "recommendedLayout": {
            "manifest": "manifest.json",
            "pagesDir": "pages/",
            "assetsDir": "assets/",
        },
    },
    "manifest": {
        "requiredFields": ["slug", "title", "brand", "season", "year", "entryHtml", "coverImage"],
        "optionalFields": [
            "reportType",
            "pages",
            "overviewHtml",
            "featuresFile",
            "lookCount",
            "version",
        ],
        "example": {
            "specVersion": "2.0",
            "reportType": "fashion_week_brief",
            "slug": "murmur-aw-2026-27-v5-2",
            "title": "Murmur 2026-27 秋冬 时装周快报",
            "brand": "Murmur",
            "season": "AW",
            "year": 2026,
            "entryHtml": "pages/report.html",
            "pages": ["pages/report.html", "pages/data.html"],
            "overviewHtml": None,
            "coverImage": "assets/cover.jpg",
            "featuresFile": "image-features.json",
            "lookCount": 38,
        },
    },
    "htmlRules": {
        "entryHtml": "必须存在，平台默认展示该 HTML 作为 iframe 入口",
        "additionalHtml": "可存在任意数量，平台不再要求 overview.html 固定命名",
        "relativeLinksOnly": "HTML/CSS/JS 中的本地资源和页面跳转必须使用 zip 内部相对路径",
    },
    "assetRules": {
        "assetDirectories": ["assets/", "images/"],
        "formats": [".jpg", ".jpeg", ".png", ".webp", ".gif", ".svg", ".json", ".css", ".js"],
        "inlineImages": "除极小图标外，不建议将正文图片以 data URI/base64 内嵌到 HTML",
        "coverImage": "必填；必须是报告第一页/首屏截图，建议使用 16:9 的 assets/cover.jpg，列表封面直接使用该文件",
    },
    "uploadBehavior": {
        "preserveRelativePaths": True,
        "entryUrlSource": "manifest.entryHtml",
        "overviewOptional": True,
        "legacyFallback": "兼容旧格式：无 manifest.json 时，要求根目录提供 index.html + cover.jpg",
    },
}
